import { access, readFile } from 'node:fs/promises';
import { isAbsolute, join } from 'node:path';
import { constants } from 'node:fs';
import { gitFor } from './repository.js';

export const BTM_HOOK_MARKER = 'btm:managed-pre-commit';

export async function resolvePreCommitHookPath(repoRoot) {
  const git = gitFor(repoRoot);
  const hookPath = await git.raw(['rev-parse', '--git-path', 'hooks/pre-commit']);
  const trimmedPath = hookPath.trim();
  return isAbsolute(trimmedPath) ? trimmedPath : join(repoRoot, trimmedPath);
}

export async function getHookStatus(hookPath) {
  const exists = await pathExists(hookPath);

  if (!exists) {
    return {
      exists: false,
      isManaged: false
    };
  }

  const contents = await readFile(hookPath, 'utf8');
  return {
    exists: true,
    isManaged: contents.includes(BTM_HOOK_MARKER)
  };
}

export function buildPreCommitHook({ cliPath }) {
  const normalizedCliPath = cliPath.replaceAll('\\', '/');

  return `#!/bin/sh
# ${BTM_HOOK_MARKER}
# Generated by BTM. Edit with care: reinstalling BTM may replace this file.

set -e

if [ -n "$BTM_CLI_PATH" ] && [ -f "$BTM_CLI_PATH" ]; then
  node "$BTM_CLI_PATH" run
elif command -v btm >/dev/null 2>&1; then
  btm run
elif [ -f "${normalizedCliPath}" ]; then
  node "${normalizedCliPath}" run
else
  npx --no-install btm run
fi
`;
}

async function pathExists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
